### ISSUE TITLE
Select-all

### ISSUE THREAD

**Issue by Atrejoe** [stevehansen/classify-data#1]
Hi Steve,

This is a great tool! I guess I'm getting old and this is the de-facto-standard now, but hosting a web-app locally and using is within a desktop app....great!
Usability: top-notch!
Saving named filters: fantastic!

One feature request though: after having applied a filter, I don't seem to be able to select all the records in order to do a batch operation: I have to select the records manually. (de-select all does exist)

Regards,

Robert

**Comment by stevehansen** [comment]
I've added code to enable select-all
