### ISSUE TITLE
Reference to non-existing NuGet package

### ISSUE THREAD

**Issue by Atrejoe** [stevehansen/classify-data#4]
Since the package upgrade, I get these messages:

```NuGet Package restore failed for project ClassifyData.App: Unable to find version '1.18.5' of package 'Vidyano.Web2'```

This version also does not appear to be listed here:

https://www.nuget.org/packages/Vidyano.Web2/

**Comment by stevehansen** [comment]
It seems the package was only pushed to our internal myget feed. I've pushed the package to the NuGet gallery. (It's currently indexing but should be available soon)

**Comment by Atrejoe** [comment]
The dependency: [Vidyano.Web2.Definition 1.18.5](https://www.nuget.org/packages/Vidyano.Web2.Definition) appear to be missing too.

**Comment by stevehansen** [comment]
My bad 😄 the definition package is also pushed

**Comment by Atrejoe** [comment]
And look at that nice green appveyor icon!
