### ISSUE TITLE
Explanation on how to edit `model.json`

### ISSUE THREAD

**Issue by Atrejoe** [stevehansen/classify-data#7]
Hi Steve,

This may be more a `vidyano` question, but do you have pointers on how to edit the `model.json` file?
I now do it by hand, but I get the feeling this file is a result of some tooling, that I don't see.

Regards,

Robert

**Comment by stevehansen** [comment]
Running the Web project (ClassifyData) directly in DEBUG instead of RELEASE should enable the Management menu item which allows you to customize the json files using the application:

![image](https://user-images.githubusercontent.com/2143488/40806389-9b46b2e6-6521-11e8-9c7c-77e05e8a4602.png)

**Comment by Atrejoe** [comment]
Ah, I was running the app (ClassifyData.App), in which these options did not appear.

Thanks!
